=== Jasig/ssp-data-migration/src/main/resources/ConfigDataTableSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

Licensed to Jasig under one or more contributor license
agreements. See the NOTICE file distributed with this work
for additional information regarding copyright ownership.
Jasig licenses this file to you under the Apache License,
Version 2.0 (the "License"); you may not use this file
except in compliance with the License. You may obtain a
copy of the License at:

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied. See the License for the
specific language governing permissions and limitations
under the License.

-->
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://http://www.jasig.org//ConfigDataTableSchema"
        xmlns:tns="http://http://www.jasig.org//ConfigDataTableSchema"
        elementFormDefault="qualified">

    <element name="configData">
        <complexType>
            <sequence>
                <element name="table" minOccurs="1" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="column" minOccurs="1"
                                     maxOccurs="unbounded">
                                <complexType>
                                    <attribute name="columnName" type="string"
                                               use="required"/>
                                </complexType>
                            </element>
                        </sequence>
                        <attribute name="tableName" type="string"
                                   use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>

</schema>

=== Jasig/ssp-data-migration/src/main/resources/BaseConfigDBSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

Licensed to Jasig under one or more contributor license
agreements. See the NOTICE file distributed with this work
for additional information regarding copyright ownership.
Jasig licenses this file to you under the Apache License,
Version 2.0 (the "License"); you may not use this file
except in compliance with the License. You may obtain a
copy of the License at:

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied. See the License for the
specific language governing permissions and limitations
under the License.

-->
<tns:configData xmlns:tns="http://http://www.jasig.org//ConfigDataTableSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://http://www.jasig.org//ConfigDataTableSchema ConfigDataTableSchema.xsd ">
  
  <tns:table tableName="campus">    
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="object_status"/>
    <tns:column columnName="early_alert_coordinator_id"/>
  </tns:table>
  
  <tns:table tableName="category">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/>      
  </tns:table>
  
  <tns:table tableName="challenge">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/>      
    <tns:column columnName="self_help_guide_description"/>
    <tns:column columnName="self_help_guide_question"/>
    <tns:column columnName="show_in_student_intake"/>
    <tns:column columnName="show_in_self_help_search"/>
    <tns:column columnName="tags character"/>
    <tns:column columnName="confidentiality_level_id"/>
  </tns:table>
  
  <tns:table tableName="challenge_category">
    <tns:column columnName="id"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/>      
    <tns:column columnName="challenge_id"/>
    <tns:column columnName="category_id"/>
  </tns:table>
  
  <tns:table tableName="challenge_challenge_referral">
    <tns:column columnName="id"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>
    <tns:column columnName="modified_by"/>
    <tns:column columnName="challenge_id"/>      
    <tns:column columnName="challenge_referral_id"/>
    <tns:column columnName="object_status"/>
  </tns:table>
  
  <tns:table tableName="challenge_referral">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/>    
    <tns:column columnName="public_description"/>
    <tns:column columnName="show_in_self_help_guide"/>
    <tns:column columnName="show_in_student_intake"/>
  </tns:table>
  
  <tns:table tableName="child_care_arrangement">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/>    
  </tns:table>
  
  <tns:table tableName="citizenship">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/>    
  </tns:table>
  
  <tns:table tableName="confidentiality_disclosure_agreement">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="text"/>    
  </tns:table>
  
  <tns:table tableName="confidentiality_level">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="acronym"/>    
    <tns:column columnName="permission"/>  
  </tns:table>
  
  <tns:table tableName="config">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="value"/>
    <tns:column columnName="value_validation"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="sort_order"/>    
    <tns:column columnName="default_value"/>  
  </tns:table>
  
  <tns:table tableName="early_alert_outcome">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="sort_order"/>    
  </tns:table>
  
  <tns:table tableName="early_alert_outreach">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="sort_order"/>    
  </tns:table>
  
  <tns:table tableName="early_alert_reason">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="sort_order"/>    
  </tns:table>
  
  <tns:table tableName="early_alert_referral">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="sort_order"/>  
    <tns:column columnName="acronym"/>   
  </tns:table>
  
  <tns:table tableName="early_alert_routing">
    <tns:column columnName="id"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="campus_id"/>  
    <tns:column columnName="early_alert_reason_id"/>      
    <tns:column columnName="person_id"/> 
    <tns:column columnName="group_name"/>  
    <tns:column columnName="group_email"/> 
  </tns:table>
  
  <tns:table tableName="early_alert_suggestion">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="sort_order"/>  
  </tns:table>
  
  <tns:table tableName="education_goal">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
    <tns:column columnName="modified_date"/>
    <tns:column columnName="created_by"/>      
    <tns:column columnName="modified_by"/>
    <tns:column columnName="object_status"/> 
    <tns:column columnName="other_description"/>  
  </tns:table>
  
  <tns:table tableName="education_level">
    <tns:column columnName="id"/>
    <tns:column columnName="name"/>    
    <tns:column columnName="description"/>
    <tns:column columnName="created_date"/>
